/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiCard: typeof import('./src/components/ApiCard.vue')['default']
    ApiDropDown: typeof import('./src/components/ApiDropDown.vue')['default']
    ApiField: typeof import('./src/components/ApiField.vue')['default']
    ApiModal: typeof import('./src/components/ApiModal.vue')['default']
    ApiNotification: typeof import('./src/components/ApiNotification.vue')['default']
    ApiSearchbar: typeof import('./src/components/ApiSearchbar.vue')['default']
    Notification: typeof import('./src/components/notification/Notification.vue')['default']
    Progress: typeof import('./src/components/notification/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
