const path = require('path');
const { defineConfig } = require('vite');
import vue from '@vitejs/plugin-vue';
import svgLoader from 'vite-svg-loader';

module.exports = defineConfig({
  plugins: [vue(), svgLoader()], // to process SFC
  resolve: {
    alias: {
      '@': path.resolve(__dirname, 'src'),
    },
  },
  build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      name: 'api-vue', // global variable name
      formats: ['es'], // adding 'umd' requires globals set to every external module
      fileName: (format) => `api-vue.${format}.js`,
    },
    rollupOptions: {
      // external modules won't be bundled into your library
      external: ['vue', 'pinia'], // not every external has a global
      output: {
        // disable warning on src/index.ts using both default and named export
        exports: 'named',
        // Provide global variables to use in the UMD build
        // for externalized deps (not useful if 'umd' is not in lib.formats)
        globals: {
          vue: 'Vue',
        },
      },
    },
    emptyOutDir: false, // to retain the types folder generated by tsc
  },
});
