import path from 'path';
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import Components from 'unplugin-vue-components/vite';
import { PrimeVueResolver } from '@primevue/auto-import-resolver';
import svgLoader from 'vite-svg-loader';

export default defineConfig({
    plugins: [
      vue(), 
      svgLoader(),
      Components({
        resolvers: [
          PrimeVueResolver(),
        ],
      }),
    ], // to process SFC
    resolve: {
        alias: {
            '@': path.resolve(__dirname, 'src'),
        },
    },
    build: {
        lib: {
            entry: path.resolve(__dirname, 'src/index.ts'),
            name: 'api-vue', // global variable name
            fileName: (format) => `api-vue.${format}.js`,
        },
        rollupOptions: {
            // external modules won't be bundled into your library
            external: ['vue', 'pinia'], // not every external has a global
            output: {
                // disable warning on src/index.ts using both default and named export
                exports: 'named',
                sourcemap: false,
                // Provide global variables to use in the UMD build
                // for externalized deps (not useful if 'umd' is not in lib.formats)
                globals: {
                    vue: 'Vue',
                    pinia: 'Pinia',
                },
            },
        },
        emptyOutDir: false, // to retain the types folder generated by tsc
    },
});
